/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.taskone.TaskOne;
import org.example.tasktwo.TaskTwo;
import org.example.taskthree.TaskThree;

public class App {
    public static void main(String[] args) {
        TaskOne.start();
        TaskTwo.start();
        TaskThree.start();
    }
}
